apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: dockergen

spec:
  replicas: 6
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 30balachandar333/dockergen-backend:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
